### ISSUE TITLE
TSIC206 - temperature sensor reading: consec_errors = 1, temp_current = 222.00

### ISSUE THREAD

**Issue by btotherunner** [lebuni/ZACwire-Library#4]
A user with us gets the following message in the Arduino monitor:

Monitor temperature sensor reading: consec_errors = 1, temp_current = 222.00

And asks if it is because he is using a TSIC206 instead of 306.

My question:
Must be: ZACwire<2> Sensor(306) to. 
ZACwire<2> Sensor(206) be changed

Greetings
Markus from the CleverCoffee team (Rancilio PID)

**Comment by TheTrueAI** [comment]
It's not necessary, because both sensors use the same protocol
