### ISSUE TITLE
Parity Problem in 1.3.1?

### ISSUE THREAD

**Issue by medlor** [lebuni/ZACwire-Library#9]
Hi Adrian,

kann es sein, dass die parity nicht mehr funktioniert? Ich erhalte nun ca alle 1500sec 2 falsche Werte (aber nie 222).

[0m(D p:^3997ms) 479 temperature sensor reading: consec_errors=1, temp_current=5.80, temp_prev=21.90
[0m(D p:^1997ms) 1932 temperature sensor reading: consec_errors=1, temp_current=9.30, temp_prev=21.90
[0m(D p:^4997ms) 1960 temperature sensor reading: consec_errors=1, temp_current=121.90, temp_prev=21.80
[0m(D p:^1997ms) 2022 temperature sensor reading: consec_errors=1, temp_current=46.80, temp_prev=22.00
[0m(D p:^0997ms) 3091 temperature sensor reading: consec_errors=1, temp_current=10.90, temp_prev=21.80
[0m(D p:^0997ms) 3141 temperature sensor reading: consec_errors=1, temp_current=46.90, temp_prev=21.80
[0m(D p:^4997ms) 3760 temperature sensor reading: consec_errors=1, temp_current=5.30, temp_prev=21.80

Ich hol mir jede Sekunde den Temp Wert.

Danke.

VG

**Comment by TheTrueAI** [comment]
Konnte ich bei mir jetzt nicht nachstellen, allerdings sieht's nach Lesefehlern aus, bei denen die beiden rawTemp aus dem ISR übernommen wurden und irgendwie nicht zusammenpassten. Ich hab mal eine beta erstellt, die das Problem hoffentlich beheben sollte.

**Comment by medlor** [comment]
Mit 1.3.2b:
ZACwire<pinTemperature> TSIC(306,125,0);

[0m(D p:^3997ms) 284 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=27.00
[0m(D p:^3997ms) 329 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=26.90
[0m(D p:^3997ms) 1604 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=26.70
[0m(D p:^1997ms) 1662 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=26.60
[0m(D p:^2997ms) 1718 temperature sensor reading: consec_errors=1, temp_current=50.00, temp_prev=26.50
[0m(D p:^2997ms) 1963 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=26.30
[0m(D p:^2997ms) 2393 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=26.30

Scheinen nun mehr Fehler reportet zu werden, aber dafür wird der Status 222 besser erkannt (ein Ausreisser?).

update:
[0m(D p:^2996ms) 2598 temperature sensor reading: consec_errors=1, temp_current=-0.70, temp_prev=26.20
[0m(D p:^4997ms) 2810 temperature sensor reading: consec_errors=1, temp_current=49.40, temp_prev=25.80

**Comment by TheTrueAI** [comment]
Ich hab leider keinen ESP32 mehr zum testen hier und der ESP8266 ließt die fehlerfreie Temperatur gefühlt auch ohne Code aus. Die beta hab ich mal geupdatet. Die Übertragung zwischen ISR und loop sieht jetzt der 1.3.0 wieder sehr ähnlich, die ja gut funktioniert hatte

**Comment by medlor** [comment]
b2:
[0m(D p:^2998ms) 38 temperature sensor reading: consec_errors=1, temp_current=18.40, temp_prev=24.70
[0m(D p:^4998ms) 550 temperature sensor reading: consec_errors=1, temp_current=11.80, temp_prev=24.30
[0m(D p:^4997ms) 1330 temperature sensor reading: consec_errors=1, temp_current=124.10, temp_prev=23.90
[0m(D p:^1997ms) 2132 temperature sensor reading: consec_errors=1, temp_current=-13.80, temp_prev=23.60
[0m(D p:^0997ms) 3061 temperature sensor reading: consec_errors=1, temp_current=-39.00, temp_prev=23.30
[0m(D p:^3997ms) 3749 temperature sensor reading: consec_errors=1, temp_current=-37.90, temp_prev=22.80

**Comment by medlor** [comment]
Ich glaub ich sollte nochmal zum Vergleich deine alte Version nehmen.

uhm.. ich denke das wäre dann der Commit https://github.com/lebuni/ZACwire-Library/commit/adc5e1d44a6da725b783393ef5c74005f95aa554 ?

**Comment by TheTrueAI** [comment]
Ne, bei dem adc5e1d hab ich noch versucht, den Core0 auf dem ESP32 dauerhaft zum laufen zu bekommen. Die 1.3.0 war wirklich die Version, die dann dauerhaft stabil lief.
https://github.com/lebuni/ZACwire-Library/blob/v1.3.0/ZACwire.h

**Comment by medlor** [comment]
v1.3.0:
1. run:
[0m(D p:^1997ms) 877 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=25.10
[0m(D p:^5000ms) 1615 Input= 25.10 | error=67.90 delta= 0.00 | Output=100.00 = b: 6.60 + p:108.64 + i: 0.00( 0.00) + d:-0.00
-> musste restarten
 
2. run:
[0m(D p:^3876ms) 1483 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=24.30
[0m(D p:^3877ms) 3043 temperature sensor reading: consec_errors=1, temp_current=-45.00, temp_prev=23.80
bis 3054s.

**Comment by TheTrueAI** [comment]
Hm, seltsam. Das lief ja damals so super sauber. Benutzt du zum Testen den gleichen Code wie vor drei Wochen (als die 1.3.0 rauskam)? Kannst du mit einem anderen TSIC gegentesten?

**Comment by medlor** [comment]
Kann morgen mal auf meiner live Maschine gegenchecken.

Aber damals lief es nur sauber auf core#1. Unter core#0 gab es schon immer Ausreißer, siehe https://github.com/lebuni/ZACwire-Library/issues/5#issuecomment-806204528. Es sind halt in der neuen Version paar mehr.

Mir ist bewusst, dass ich nur auf die Logs schaue, daher ist da auch eine gewisse Unschärfe dabei. Mitunter weiss ich auch nicht, ob deine neue Version einfach nur penibler Fehler meldet und diese in der alten durch das Backup einfach "verschluckt" wurden.


Hier noch ein run mit 1.3.0:
[0m(D p:^2997ms) 663 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=24.70
[0m(D p:^4997ms) 1510 temperature sensor reading: consec_errors=1, temp_current=12.30, temp_prev=24.40
[0m(D p:^4997ms) 2245 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=24.10
[0m(D p:^2997ms) 2398 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=24.10
[0m(D p:^2997ms) 3538 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=23.90
[0m(D p:^3997ms) 5799 temperature sensor reading: consec_errors=1, temp_current=222.00, temp_prev=23.10
bis 5910

**Comment by TheTrueAI** [comment]
Ich hab mir jetzt endlich auch einen ESP32 zugelegt und kann nun testen. Funktioniert dein Test-Code auch ohne weitere Verkabelung oder lokalen Server? Schick mal einen Link zum Code!
Mit dem Beispiel-Code der library lief der ESP32 auf v1.3.2b4 schon über 1,3 Mio. Temperatusauslesungen fehlerfrei

**Comment by medlor** [comment]
Die obigen logs habe ich direkt mit dem unveränderten (jeweilig aktuellen) master-code bestimmt. Den Stand kannst du mit nur dem temp-sensor auch laufen lassen hierzu folgendes tun:
1) https://github.com/medlor/bleeding-edge-ranciliopid auschecken/downloaden
2) userConfig.h.Sample in userConfig.h umbenennen und dort dann folgende Felder anpassen:
2.1) #define DEBUGMODE (auskommentieren)
2.2) #define pinTemperature    26    (auf den GPIO Pin stellen, an welchem du deinen temp sensor hängen hast. hier GPIO26)
2.3) WLAN/OTA Netzwerk stuff unter paragraph "networking and services" anpassen
3) Upload via arduino
4) telnet <your-ip> 23  (to access the debug logs, or use serial window)

Bei Fragen einfach im discord melden.
Wenn nötig, dann kann ich schauen den Code nochmal zu minimieren.

PS.: Ich würde vermuten, dass es nebenläufig effekte gibt, die zu diesen Lesefehlern führen. Vorallem weil diese ja nur auf core#0 auftreten.

**Comment by medlor** [comment]
Ok, konnte das Problem mit einem sehr kleinen Code nachstellen.

Hierzu bitte folgenden Code im Folder zum Testen nehmen. Sobald ich im Code den EEPROM Teil auskommentiere, habe ich keine Fehler mehr.

https://github.com/medlor/bleeding-edge-ranciliopid/tree/2.7.1/rancilio-pid/src/ZACWire-test

Log:
0 temp=222.00
EEPROM: sync_eeprom
EEPROM: sync_eeprom() finished
300 temp=222.00
EEPROM: sync_eeprom
EEPROM: sync_eeprom() finished
600 temp=222.00
EEPROM: sync_eeprom
EEPROM: sync_eeprom() finished
900 temp=222.00

**Comment by TheTrueAI** [comment]
Sehr interessant! Scheinbar wird nicht jede rising edge erkannt, während die Preferences library läuft. Internal interrupts funktionieren mit der Preference library noch zuverlässig. Vielleicht starte ich da mal einen Issue...

Mit der v1.3.2b6 konnte ich die Fehler verringern, aber komplett eliminieren ging leider aufgrund der fehlenden Bits nicht. Dann muss man vorerst schauen, dass man die Preferences.h nicht zu häufig aufruft

**Comment by medlor** [comment]
Freut mich, dass ich helfen konnte.
Meine Vermutung wäre gewesen, dass es nicht zwingend an der Preference liegt, sondern eher am arduino-esp32 der bei "langlaufenden system prozessen auf core0" unsere Interrupts  stört.
 
Ich teste mal die v1.3.2b6 .

**Comment by medlor** [comment]
Habe nun keinen Fehler mehr bei <3000s bemerkt. Super!
